# ---------------------------------------------------------------------------
# 功能：1、提取出LAI栅格中”<100"的有效值
#       2、分植被类型进行LAI均值计算
# Created on: 星期日 十二月 18 2011 02:37:43 下午
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

#循环开始
for n in xrange(2000,2012):
	i=0
	for d in xrange(1,365,8):
		d="%03d" % d
		data_class="LAI"
##########################-----操作目录---------##############################################
		input_mulu="E:\\HUC\\data\\"		#输入TIF文件目录		
		out_mulu="d:\\linshi\\"	#输出有效值文件目录


		
##########################-----输入文件---------##############################################
		input_tif1 = input_mulu+"MOD15A2.A"+str(n)+d+".Lai_1km.tif" 
		input_tif = input_mulu+"MOD15A2.A"+str(n)+d+"clip.tif" 		
		output_extra = out_mulu+"lai"+str(n)+d+".tif"	#提取后输出的tif文件

		basin_clip="H:\\流域划分\\HUC\\basin_buffer_pro.shp"
			
		print output_extra,output_data_basin_1
		
# Process: 裁剪 (3)
		arcpy.Clip_management(input_tif1, "-569482.72309382 3210242.66760919 -96637.2454170428 3594357.64348364", input_tif, basin_clip, "", "ClippingGeometry")	

			
# Process: Extract by Attributes...
		arcpy.gp.ExtractByAttributes_sa(input_tif ,"\"value\" < 100 ", output_extra)
		print "成功提取出“<100“的值！"
