# ---------------------------------------------------------------------------
# 功能：1、提取出LAI栅格中”<100"的有效值
#       2、分植被类型进行LAI均值计算
# Created on: 星期日 十二月 18 2011 02:37:43 下午
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

#循环开始
for n in xrange(2006,2007):
#	for m in xrange(1,13):
#		m=range(1,13)
#		m="%02d" % m
	i=0
	for d in xrange(1,365,8):
		d="%03d" % d
		data_class="LAI"
##########################-----操作目录---------##############################################
		input_mulu="E:\\HUC\\data\\"		#输入TIF文件目录		
		out_mulu="d:\\"	#输出有效值文件目录
		out_mulu_lai="D:\\\WASSI\\\ChangJiang\\"	#输出LAI计算结果目录
		input_mulu_basin="D:\\WASSI\\ChangJiang\\VEG_CJ\\"
		basins_dir="E:\\HUC\\VEG\\"
##########################-----输入文件---------##############################################
		input_tif = input_mulu+"MOD15A2.A"+str(n)+d+".Lai_1km.tif"  
		output_extra = out_mulu+"MOD15A2.A"+str(n)+d+".Lai_1km.extra.tif"	#提取后输出的tif文件
		name4=data_class+str(n)+d+".dbf"
##########################-----输入basin文件---------##############################################			
		basin_num_1="15"
		basin_num_2="20"
		basin_num_3="25"
		basin_num_4="30"
		basin_num_5="35"
		basin_num_6="45"
		basin_num_7="60"
		basin_num_8="80"
		basin_num_9="120"
		basin_num_10="200"
		basin_num_11="300"
		basin_num_12="458"
		basin_num_13="650"
		basin_num_14="1500"
		basin_num_15="4000"
		basin_num_16="20000"
		basin_num_17="20000"
		basin_num_18="2000"
			
		basin_1=basins_dir+"VEG_"+basin_num_1+".shp"	# 待统计流域边界
		basin_2=basins_dir+"VEG_"+basin_num_2+".shp"	# 待统计流域边界
		basin_3=basins_dir+"VEG_"+basin_num_3+".shp"	# 待统计流域边界
		basin_4=basins_dir+"VEG_"+basin_num_4+".shp"	# 待统计流域边界
		basin_5=basins_dir+"VEG_"+basin_num_5+".shp"	# 待统计流域边界
		basin_6=basins_dir+"VEG_"+basin_num_6+".shp"	# 待统计流域边界
		basin_7=basins_dir+"VEG_"+basin_num_7+".shp"	# 待统计流域边界
		basin_8=basins_dir+"VEG_"+basin_num_8+".shp"	# 待统计流域边界
		basin_9=basins_dir+"VEG_"+basin_num_9+".shp"	# 待统计流域边界
		basin_10=basins_dir+"VEG_"+basin_num_10+".shp"	# 待统计流域边界
		basin_11=basins_dir+"VEG_"+basin_num_11+".shp"	# 待统计流域边界
		basin_12=basins_dir+"VEG_"+basin_num_12+".shp"	# 待统计流域边界
		basin_13=basins_dir+"VEG_"+basin_num_13+".shp"	# 待统计流域边界
		basin_14=basins_dir+"VEG_"+basin_num_14+".shp"	# 待统计流域边界
		basin_15=basins_dir+"VEG_"+basin_num_15+".shp"	# 待统计流域边界
		basin_16=basins_dir+"VEG_"+basin_num_16+".shp"	# 待统计流域边界
		basin_17=basins_dir+"VEG_"+basin_num_17+".shp"	# 待统计流域边界
		basin_18=basins_dir+"VEG_"+basin_num_18+".shp"	# 待统计流域边界
######################-----分植被类型处理后的结果文件------##############################################
		output_data_dir_basin_1="E:\\HUC\\basin_"+basin_num_1+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_2="E:\\HUC\\basin_"+basin_num_2+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_3="E:\\HUC\\basin_"+basin_num_3+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_4="E:\\HUC\\basin_"+basin_num_4+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_5="E:\\HUC\\basin_"+basin_num_5+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_6="E:\\HUC\\basin_"+basin_num_6+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_7="E:\\HUC\\basin_"+basin_num_7+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_8="E:\\HUC\\basin_"+basin_num_8+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_9="E:\\HUC\\basin_"+basin_num_9+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_10="E:\\HUC\\basin_"+basin_num_10+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_11="E:\\HUC\\basin_"+basin_num_11+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_12="E:\\HUC\\basin_"+basin_num_12+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_13="E:\\HUC\\basin_"+basin_num_13+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_14="E:\\HUC\\basin_"+basin_num_14+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_15="E:\\HUC\\basin_"+basin_num_15+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_16="E:\\HUC\\basin_"+basin_num_16+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_17="E:\\HUC\\basin_"+basin_num_17+"\\"+data_class+"\\"	#统计结果输出的目录
		output_data_dir_basin_18="E:\\HUC\\basin_"+basin_num_18+"\\"+data_class+"\\"	#统计结果输出的目录





		output_data_basin_1=output_data_dir_basin_1+name4	#按表格统计结果输出的文件
		output_data_basin_2=output_data_dir_basin_2+name4	#按表格统计结果输出的文件
		output_data_basin_3=output_data_dir_basin_3+name4	#按表格统计结果输出的文件
		output_data_basin_4=output_data_dir_basin_4+name4	#按表格统计结果输出的文件
		output_data_basin_5=output_data_dir_basin_5+name4	#按表格统计结果输出的文件
		output_data_basin_6=output_data_dir_basin_6+name4	#按表格统计结果输出的文件
		output_data_basin_7=output_data_dir_basin_7+name4	#按表格统计结果输出的文件
		output_data_basin_8=output_data_dir_basin_8+name4	#按表格统计结果输出的文件
		output_data_basin_9=output_data_dir_basin_9+name4	#按表格统计结果输出的文件
		output_data_basin_10=output_data_dir_basin_10+name4	#按表格统计结果输出的文件
		output_data_basin_11=output_data_dir_basin_11+name4	#按表格统计结果输出的文件
		output_data_basin_12=output_data_dir_basin_12+name4	#按表格统计结果输出的文件
		output_data_basin_13=output_data_dir_basin_13+name4	#按表格统计结果输出的文件
		output_data_basin_14=output_data_dir_basin_14+name4	#按表格统计结果输出的文件
		output_data_basin_15=output_data_dir_basin_15+name4	#按表格统计结果输出的文件
		output_data_basin_16=output_data_dir_basin_16+name4	#按表格统计结果输出的文件
		output_data_basin_17=output_data_dir_basin_17+name4	#按表格统计结果输出的文件
		output_data_basin_18=output_data_dir_basin_18+name4	#按表格统计结果输出的文件
			
			
		print output_extra,output_data_basin_1

			
# Process: Extract by Attributes...
		arcpy.gp.ExtractByAttributes_sa(input_tif ,"\"value\" < 100 ", output_extra)
		print "成功提取出“<100“的值！"
			

# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
		arcpy.gp.ZonalStatisticsAsTable_sa(basin_1, "FID", output_extra, output_data_basin_1, "DATA", "MEAN")
		print "成功对basin_250进行统计"
		
# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
		arcpy.gp.ZonalStatisticsAsTable_sa(basin_2, "FID", output_extra, output_data_basin_2, "DATA", "MEAN")
		print "成功对basin_500进行统计"

# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
		arcpy.gp.ZonalStatisticsAsTable_sa(basin_3, "FID", output_extra, output_data_basin_3, "DATA", "MEAN")
		print "成功对basin_800进行统计"

# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
		arcpy.gp.ZonalStatisticsAsTable_sa(basin_4, "FID", output_extra, output_data_basin_4, "DATA", "MEAN")
		print "成功对basin_1200进行统计"

# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
		arcpy.gp.ZonalStatisticsAsTable_sa(basin_5, "FID", output_extra, output_data_basin_5, "DATA", "MEAN")
		print "成功对basin_1500进行统计"


# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
		arcpy.gp.ZonalStatisticsAsTable_sa(basin_6, "FID", output_extra, output_data_basin_6, "DATA", "MEAN")
		print "成功对basin_2000进行统计"
		
# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
		arcpy.gp.ZonalStatisticsAsTable_sa(basin_7, "FID", output_extra, output_data_basin_7, "DATA", "MEAN")
		print "成功对basin_250进行统计"
		
# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
		arcpy.gp.ZonalStatisticsAsTable_sa(basin_8, "FID", output_extra, output_data_basin_8, "DATA", "MEAN")
		print "成功对basin_500进行统计"

# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
		arcpy.gp.ZonalStatisticsAsTable_sa(basin_9, "FID", output_extra, output_data_basin_9, "DATA", "MEAN")
		print "成功对basin_800进行统计"

# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
		arcpy.gp.ZonalStatisticsAsTable_sa(basin_10, "FID", output_extra, output_data_basin_10, "DATA", "MEAN")
		print "成功对basin_1200进行统计"

# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
		arcpy.gp.ZonalStatisticsAsTable_sa(basin_11, "FID", output_extra, output_data_basin_11, "DATA", "MEAN")
		print "成功对basin_1500进行统计"


# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
		arcpy.gp.ZonalStatisticsAsTable_sa(basin_12, "FID", output_extra, output_data_basin_12, "DATA", "MEAN")
		print "成功对basin_2000进行统计"
# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
		arcpy.gp.ZonalStatisticsAsTable_sa(basin_13, "FID", output_extra, output_data_basin_13, "DATA", "MEAN")
		print "成功对basin_250进行统计"
		
# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
		arcpy.gp.ZonalStatisticsAsTable_sa(basin_14, "FID", output_extra, output_data_basin_14, "DATA", "MEAN")
		print "成功对basin_500进行统计"

# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
		arcpy.gp.ZonalStatisticsAsTable_sa(basin_15, "FID", output_extra, output_data_basin_15, "DATA", "MEAN")
		print "成功对basin_800进行统计"

# Process: 以表格显示分区统计岷江流域
# Process: Zonal Statistics as Table...
		arcpy.gp.ZonalStatisticsAsTable_sa(basin_16, "FID", output_extra, output_data_basin_16, "DATA", "MEAN")
		print "成功对basin_1200进行统计"

		
# Process: Delete...
		arcpy.gp.Delete_management(output_extra, "RasterDataset")
		print "成功删除TIF影像文件"
