# ---------------------------------------------------------------------------
# 0002.py
# Created on: 2012-04-18 14:40:49.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

for n in xrange(2000,2001):
#	for m in xrange(1,13):
#		m="%02d" % m		#转换为两位日期
		
		
		
	input_lai_mulu="d:\\linshi\\"
	out_lai_mu="e:\\out\\"	
# Local variables:
	input_lai_1= input_lai_mulu+"lai"+str(n)+"001.tif"
	input_lai_2= input_lai_mulu+"lai"+str(n)+"009.tif"
	input_lai_3= input_lai_mulu+"lai"+str(n)+"017.tif"
	input_lai_4= input_lai_mulu+"lai"+str(n)+"025.tif"
	
	input_lai_5= input_lai_mulu+"lai"+str(n)+"033.tif"
	input_lai_6= input_lai_mulu+"lai"+str(n)+"041.tif"
	input_lai_7= input_lai_mulu+"lai"+str(n)+"049.tif"
	input_lai_8= input_lai_mulu+"lai"+str(n)+"057.tif"
	
	input_lai_9= input_lai_mulu+"lai"+str(n)+"065.tif"
	input_lai_10= input_lai_mulu+"lai"+str(n)+"073.tif"
	input_lai_11= input_lai_mulu+"lai"+str(n)+"081.tif"
	input_lai_12= input_lai_mulu+"lai"+str(n)+"089.tif"
	
	input_lai_13= input_lai_mulu+"lai"+str(n)+"097.tif"
	input_lai_14= input_lai_mulu+"lai"+str(n)+"105.tif"
	input_lai_15= input_lai_mulu+"lai"+str(n)+"113.tif"
	
	input_lai_16= input_lai_mulu+"lai"+str(n)+"121.tif"
	input_lai_17= input_lai_mulu+"lai"+str(n)+"129.tif"
	input_lai_18= input_lai_mulu+"lai"+str(n)+"137.tif"
	input_lai_19= input_lai_mulu+"lai"+str(n)+"145.tif"
	
	input_lai_20= input_lai_mulu+"lai"+str(n)+"153.tif"
	input_lai_21= input_lai_mulu+"lai"+str(n)+"161.tif"
	input_lai_22= input_lai_mulu+"lai"+str(n)+"169.tif"
	input_lai_23= input_lai_mulu+"lai"+str(n)+"177.tif"
	
	input_lai_24= input_lai_mulu+"lai"+str(n)+"185.tif"
	input_lai_25= input_lai_mulu+"lai"+str(n)+"193.tif"
	input_lai_26= input_lai_mulu+"lai"+str(n)+"201.tif"
	input_lai_27= input_lai_mulu+"lai"+str(n)+"209.tif"
	
	input_lai_28= input_lai_mulu+"lai"+str(n)+"217.tif"
	input_lai_29= input_lai_mulu+"lai"+str(n)+"225.tif"
	input_lai_30= input_lai_mulu+"lai"+str(n)+"233.tif"
	input_lai_31= input_lai_mulu+"lai"+str(n)+"241.tif"
	
	input_lai_32= input_lai_mulu+"lai"+str(n)+"249.tif"
	input_lai_33= input_lai_mulu+"lai"+str(n)+"257.tif"
	input_lai_34= input_lai_mulu+"lai"+str(n)+"265.tif"
	input_lai_35= input_lai_mulu+"lai"+str(n)+"273.tif"
	
	input_lai_36= input_lai_mulu+"lai"+str(n)+"281.tif"
	input_lai_37= input_lai_mulu+"lai"+str(n)+"289.tif"
	input_lai_38= input_lai_mulu+"lai"+str(n)+"297.tif"
	
	input_lai_39= input_lai_mulu+"lai"+str(n)+"305.tif"
	input_lai_40= input_lai_mulu+"lai"+str(n)+"313.tif"
	input_lai_41= input_lai_mulu+"lai"+str(n)+"321.tif"
	input_lai_42= input_lai_mulu+"lai"+str(n)+"329.tif"

	input_lai_43= input_lai_mulu+"lai"+str(n)+"337.tif"
	input_lai_44= input_lai_mulu+"lai"+str(n)+"345.tif"
	input_lai_45= input_lai_mulu+"lai"+str(n)+"353.tif"
	input_lai_46= input_lai_mulu+"lai"+str(n)+"361.tif"

	
	
	out_lai_01_tif=out_lai_mu+"lai"+str(n)+"01.tif"
	out_lai_02_tif=out_lai_mu+"lai"+str(n)+"02.tif"
	out_lai_03_tif=out_lai_mu+"lai"+str(n)+"03.tif"
	out_lai_04_tif=out_lai_mu+"lai"+str(n)+"04.tif"
	out_lai_05_tif=out_lai_mu+"lai"+str(n)+"05.tif"
	out_lai_06_tif=out_lai_mu+"lai"+str(n)+"06.tif"
	out_lai_07_tif=out_lai_mu+"lai"+str(n)+"07.tif"
	out_lai_08_tif=out_lai_mu+"lai"+str(n)+"08.tif"
	out_lai_09_tif=out_lai_mu+"lai"+str(n)+"09.tif"
	out_lai_10_tif=out_lai_mu+"lai"+str(n)+"10.tif"
	out_lai_11_tif=out_lai_mu+"lai"+str(n)+"11.tif"
	out_lai_12_tif=out_lai_mu+"lai"+str(n)+"12.tif"
# Process: 像元统计数据
	arcpy.gp.CellStatistics_sa([input_lai_1,input_lai_2,input_lai_3,input_lai_4],out_lai_01_tif,"MEAN","DATA")
	arcpy.gp.CellStatistics_sa([input_lai_5,input_lai_6,input_lai_7,input_lai_8], out_lai_02_tif, "MEAN", "DATA")
	arcpy.gp.CellStatistics_sa([input_lai_9,input_lai_10,input_lai_11,input_lai_12], out_lai_03_tif, "MEAN", "DATA")
	arcpy.gp.CellStatistics_sa([input_lai_13,input_lai_14,input_lai_15], out_lai_04_tif, "MEAN", "DATA")
	arcpy.gp.CellStatistics_sa([input_lai_16,input_lai_17,input_lai_18,input_lai_19], out_lai_05_tif, "MEAN", "DATA")
	arcpy.gp.CellStatistics_sa([input_lai_20,input_lai_21,input_lai_22,input_lai_23], out_lai_06_tif, "MEAN", "DATA")
	arcpy.gp.CellStatistics_sa([input_lai_24,input_lai_25,input_lai_26,input_lai_27], out_lai_07_tif, "MEAN", "DATA")
	arcpy.gp.CellStatistics_sa([input_lai_28,input_lai_29,input_lai_30,input_lai_31], out_lai_08_tif, "MEAN", "DATA")
	arcpy.gp.CellStatistics_sa([input_lai_32,input_lai_33,input_lai_34,input_lai_35], out_lai_09_tif, "MEAN", "DATA")
	arcpy.gp.CellStatistics_sa([input_lai_36,input_lai_37,input_lai_38], out_lai_10_tif, "MEAN", "DATA")
	arcpy.gp.CellStatistics_sa([input_lai_39,input_lai_40,input_lai_41,input_lai_42], out_lai_11_tif, "MEAN", "DATA")
	arcpy.gp.CellStatistics_sa([input_lai_43,input_lai_44,input_lai_45,input_lai_46], out_lai_12_tif, "MEAN", "DATA")
	print "完成年内的各月LAI合并！"
